// STRIPE CONSTANTS
export const DO_GET_INDENT = "DO_GET_INDENT"
export const DO_STRIPE_PAY = "DO_STRIPE_PAY"

// ORDER CONSTANTS
export const DO_CREATE_ORDER = "DO_CREATE_ORDER"

// COMMENT CONSTANTS
export const DO_CREATE_COMMENT = "DO_CREATE_COMMENT"


export const CHANGE_PHONE_NUMBER = "CHANGE_PHONE_NUMBER"
export const CHANGE_EMAIL_ADDRESS = "CHANGE_EMAIL_ADDRESS"
export const CHANGE_SHIPPING_FIRSTNAME = "CHANGE_SHIPPING_FIRSTNAME"
export const CHANGE_SHIPPING_LASTNAME = "CHANGE_SHIPPING_LASTNAME"
export const CHANGE_SHIPPING_COMPANY = "CHANGE_SHIPPING_COMPANY"
export const CHANGE_SHIPPING_STREET_ONE = "CHANGE_SHIPPING_STREET_ONE"
export const CHANGE_SHIPPING_CITY = "CHANGE_SHIPPING_CITY"
export const CHANGE_SHIPPING_STATE = "CHANGE_SHIPPING_STATE"
export const CHANGE_SHIPPPING_ZIP = "CHANGE_SHIPPPING_ZIP"
export const CHANGE_BILLING_EMAIL = "CHANGE_BILLING_EMAIL"
export const CHANGE_BILLING_STREET_ONE = "CHANGE_BILLING_STREET_ONE"
export const CHANGE_BILLING_STREET_TWO = "CHANGE_BILLING_STREET_TWO"
export const CHANGE_BILLING_CITY = "CHANGE_BILLING_CITY"
export const CHANGE_BILLING_STATE = "CHANGE_BILLING_STATE"
export const BILLING_SHIPPING_SAME = "BILLING_SHIPPING_SAME"
export const CHANGE_ABANDON_USER = "CHANGE_ABANDON_USER"